### PR TITLE
App ci fixes

### PR DESCRIPTION
**Pull request by jjgriff93**
- Fixes an issue where having no app.{ENVIRONMENT}.yaml when deploying causes a null iterator error
- Adds a PR suffix to an app_id if suffix_override is specified, to fix conflicts with existing apps in PR environments

### CODE REVIEW

**Review by t-young31 — APPROVED** [review]
thanks 🙏🏼

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4536176040 (with refid `cb8f4205`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/211#issuecomment-1485802400) from @jjgriff93)

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4537220001 (with refid `cb8f4205`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/211#issuecomment-1485947969) from @jjgriff93)

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4537275987 (with refid `cb8f4205`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/211#issuecomment-1485954836) from @jjgriff93)

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4537543519 (with refid `cb8f4205`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/211#issuecomment-1485990272) from @jjgriff93)

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

Destroying environment (with refid cb8f4205)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/211#issuecomment-1486005270) from @jjgriff93)

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

Destroying environment no terraform (with refid cb8f4205).	:warning: This will leave orphaned resources

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/211#issuecomment-1486010290) from @jjgriff93)

**Comment by jjgriff93** [comment]
/test-force-approve
Tests have passed, destroy failed (known issue)

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

:white_check_mark: Marking tests as complete (for commit 458e5db720414df88beb0006fdc7966d2cfc426c)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/211#issuecomment-1486010667) from @jjgriff93)

**Pull request merged**
