### PR TITLE
Added missing azure-tenant-id secret to databricks

### PR DESCRIPTION
**Pull request by damoodamoo**
Found `azure-tenant-id` was expected in pipeline code, but missing from databricks secrets. This adds it in.

### CODE REVIEW

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6260489355 (with refid `a1e90952`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/331#issuecomment-1729301503) from @damoodamoo)

**Review by jjgriff93 — APPROVED** [review]

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6273489000 (with refid `a1e90952`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/331#issuecomment-1731234298) from @jjgriff93)

**Comment by tanya-borisova** [comment]
Confused. Why do we need this? Why can’t we just add the secret through the config, same way as cognitive services key is added in?

**Review by tanya-borisova — CHANGES_REQUESTED** [review]
Don’t think we need this

**Review by stefpiatek — COMMENTED** [review]
LGTM, `\test` doesn't seem to pass, though seems unrelated to these changes. I presume we care about this passing so should fix it to get these changes in?

**Review by stefpiatek — APPROVED** [review]
... should've hit approve 🤦

**Review by tanya-borisova — APPROVED** [review]
@damoodamoo  convinced me that this secret better lives upstream so I'm approving this :)

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6417061708 (with refid `a1e90952`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/331#issuecomment-1748453777) from @jjgriff93)

**Pull request merged**
