### PR TITLE
Provide an optional SHA for data pipeline repo

### PR DESCRIPTION
**Pull request by tanya-borisova**
Provide an optional SHA for data pipeline repo so that we can fix it on a commit in data-forge

### CODE REVIEW

**Review by damoodamoo — APPROVED** [review]
Yea great idea.

**Review by jjgriff93 — APPROVED** [review]
Great stuff - only comment is I think we should show that the sea is optional by getting rid of the first item's sha in the sample instead of the `""`

**Comment by tanya-borisova** [comment]
/test-force-approve 

Something still doesn't work in apps area (cc @jjgriff93 )

**Pull request merged**
