### PR TITLE
Add missing actions:read scope to GH App scopes

### PR DESCRIPTION
**Pull request by jjgriff93**
Fix for issue we're facing on private UCLH fork when deploying a private app

Requests to the deployment environments API require `actions: read-only` scopes for GitHub Apps when querying private repos, which is why it's worked for public. The knock-on effect was causing the GitHub TF provider to crash, which is a bad error handling bug that ive raised an issue on the provide for.

### CODE REVIEW

**Review by damoodamoo — APPROVED** [review]
nice catch mate

**Review by t-young31 — APPROVED** [review]
Amazing catch

**Comment by jjgriff93** [comment]
/test-force-approve

Docs update

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:white_check_mark: Marking tests as complete (for commit 5cbd4c21af595a1b3c350a8123bf71ac0e25b91c)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/263#issuecomment-1514351962) from @jjgriff93)

**Pull request merged**
