### PR TITLE
Use log analytics retention policy for diagnostics

### PR DESCRIPTION
**Pull request by stefpiatek**
# Resolves 320

## What is being addressed

When building any new resources that have a `retention_policy` in their diagnostic settings there is now an error returned from azure:

```
Message="Diagnostic settings does not support retention for new diagnostic settings."
```

## How is this addressed

- Remove `retention_policy` blocks from azure monitor diagnostic settings
- Falling back to the log analytics retention policy

### CODE REVIEW

**Review by dram1964 — APPROVED** [review]

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6224972382 (with refid `f195aea0`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/328#issuecomment-1723793602) from @stefpiatek)

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6224972382 (with refid `f195aea0`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/328#issuecomment-1723793602) from @stefpiatek)

**Review by marrobi — APPROVED** [review]
LGTM

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6296819382 (with refid `f195aea0`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/328#issuecomment-1733165043) from @stefpiatek)

**Pull request merged**
