### PR TITLE
CIS compliance: storage

### LINKED ISSUE #176: Storage Accounts: CIS
For all storage accounts, including management:
- [ ] Enable infrastructure encryption
- [ ] Soft Delete Enabled
- [ ] Disable Blob Public Access
- [ ] Diagnostic settings for blob: read / write / delete tracked

To discuss: 

- [x] public network access for Management Storage Account. Resolved with #199 
- [x]  remove key access to storage and use only AAD auth?

can't use no keys: 

```
  │ Error: reading queue properties for AzureRM Storage Account "strgflwrd1a9461e": queues.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account.\nRequestId:75cbfa8d-9003-00a6-5c14-62153e000000\nTime:2023-03-29T08:03:49.1630361Z"
```

### PR DESCRIPTION
**Pull request by t-young31**
# Resolves #176 

### What is being addressed

Adds configuration to the two FlowEHR storage accounts for CIS compliance.

### Questions

- [x] Will setting [shared_access_key_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#shared_access_key_enabled) `= false` break anything?

### CODE REVIEW

**Comment by jjgriff93** [comment]
I don't _think_ anything is used the shared access key so you should be ok to disable it

**Review by jjgriff93 — APPROVED** [review]
Looks good!

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4551602651 (with refid `d1a9461e`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/217#issuecomment-1488114058) from @t-young31)

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4551725393 (with refid `d1a9461e`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/217#issuecomment-1488133531) from @t-young31)

**Comment by jjgriff93** [comment]
> > I don't think anything is used the shared access key so you should be ok to disable it
> 
> no dice 😞
> 
> ```
>   │ Error: reading queue properties for AzureRM Storage Account "strgflwrd1a9461e": queues.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account.\nRequestId:75cbfa8d-9003-00a6-5c14-62153e000000\nTime:2023-03-29T08:03:49.1630361Z"
> ```

Why on earth is it reading queue properties?

**Comment by jjgriff93** [comment]
We don't use storage queues so probably need to find out what's doing a GET on that

**Comment by jjgriff93** [comment]
We can potentially just set the storage account kind to BlobStorage so we only have blob enabled and queues are disabled

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#account_kind

**Review by damoodamoo — APPROVED** [review]

**Comment by t-young31** [comment]
Need keys for: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server_vulnerability_assessment

**Comment by t-young31** [comment]
/test-force-approve

Test failed on cleanup and discussed other points

**Pull request merged**
