### PR TITLE
Add action comment for destroy

### LINKED ISSUE #38: Deployment fails with a `truncated_naming_prefix` of 20 chars
The first deployment to Infra-Test failed due to the truncated naming prefix + `amlstrg` exceeding the number of characters allowed for an azure storage account. `truncated_naming_prefix` should be fewer than 18 chars?

### LINKED ISSUE #44: PR bot doesn't add a comment when destroying an env

### LINKED ISSUE #47: PR test for PRs that don't change any infrastructure skip summary step (reporting successful check)
Example: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4054081772

### PR DESCRIPTION
**Pull request by t-young31**
### Fixes #47

### CODE REVIEW

**Comment by t-young31** [comment]
will test on my fork if necessary 😅

**Review by jjgriff93 — APPROVED** [review]

**Pull request merged**
