### PR TITLE
Fix Databricks provider version

### PR DESCRIPTION
**Pull request by tanya-borisova**
## What is being addressed

Recent pull request https://github.com/UCLH-Foundry/FlowEHR/pull/326 contains a bug: creation of databricks_metastore_assignment would sometimes error out with a message like "Storage credential XXX doesn't exist", and creation of metastore_data_access would also error out with a message like "No metastore assigned to the current workspace".

This has been fixed by upgrading the version of the provider to a newer one, and moving to account-level provider for these resources.
For more information, see https://github.com/databricks/terraform-provider-databricks/pull/2182 

Additional change I have made is now catalog name and schema name for Unity Catalog are passed in as Spark secrets, as opposed to pipeline inputs.

### CODE REVIEW

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6240681607 (with refid `dac8a372`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/329#issuecomment-1726432509) from @tanya-borisova)

**Review by martinpeck — APPROVED** [review]

**Review by jjgriff93 — APPROVED** [review]

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6247966214 (with refid `dac8a372`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/329#issuecomment-1727546369) from @jjgriff93)

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6248597981 (with refid `dac8a372`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/329#issuecomment-1727634322) from @jjgriff93)

**Pull request merged**
