### PR TITLE
Automatically create dashboards for data pipelines

### LINKED ISSUE #18: Initial Databricks Terraform configuration
As a Data / Infra Engineer, 
I want to have Databricks deployed via Terraform, 
So that I can create repeatable throwaway deployments for my own testing. 

Acceptance criteria
- [ ] Databricks Workspace deployed
- [ ] Job Compute cluster configured (smallest cluster possible)

### PR DESCRIPTION
**Pull request by tanya-borisova**
# Resolves #18

## What is being addressed

Automatically create 3 dashboards for the data pipeline with pipeline successes, failures, and rows written to the database:

image

### CODE REVIEW

**Review by jedheaj314 — APPROVED** [review]

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4877947617 (with refid `ccac6a35`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/289#issuecomment-1533924276) from @tanya-borisova)

**Review by jedheaj314 — APPROVED** [review]

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4881149162 (with refid `ccac6a35`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/289#issuecomment-1534383540) from @tanya-borisova)

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4881336690 (with refid `ccac6a35`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/289#issuecomment-1534430955) from @tanya-borisova)

**Pull request merged**
