### PR TITLE
Config.Sample Note

### PR DESCRIPTION
**Pull request by damoodamoo**
During the unity catalog deployment it appears that we get inconsistencies if the zone names have capital letters in them. This updates the sample to recommend lower case names.

### CODE REVIEW

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/6251285334 (with refid `6a654d83`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/330#issuecomment-1728049710) from @damoodamoo)

**Review by stefpiatek — APPROVED** [review]

**Review by jjgriff93 — APPROVED** [review]

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:white_check_mark: Marking tests as complete (for commit e2ac84923fd51758b7b8302a293b54e45445fb03)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/330#issuecomment-1731232249) from @jjgriff93)

**Pull request merged**
