### PR TITLE
Adding SQL users / groups

### PR DESCRIPTION
**Pull request by damoodamoo**
Fixes issue with accounts / groups not being added as SQL users due to an invalid role name being used.

Tested it on Infra Test to make sure changes are picked up, here: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4503156588

### CODE REVIEW

**Review by t-young31 — APPROVED** [review]

**Comment by t-young31** [comment]
(would appreciate a rebase onto main to make the commit messages nicer)

**Review by jjgriff93 — APPROVED** [review]

**Comment by t-young31** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4533585670 (with refid `eb998ae7`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/207#issuecomment-1485309354) from @damoodamoo)

**Review by martinpeck — APPROVED** [review]

**Pull request merged**
