### PR TITLE
Add flowehr prefix to state & dns zone + makefile fix

### LINKED ISSUE #249: make all doesn't build transform artefacts
The `transform-artifacts` make dependency isn't invoked in current CI builds

### LINKED ISSUE #250: Postgres data sources dns zone not linked to
Because data sources require additional dns zones that in CI are deployed by bootstrap, FlowEHR needs to be able to reference the bootstrap resource group instead of the data sources resource group when vnet linking to the dns zones. 

This should be dependent on whether the `private_dns_zones_rg` config value is defined or not

### LINKED ISSUE #251: FlowEHR state folder path missing prefix
Because all state is now stored in the single CI bootstrap blob container, and that handles deployments not just for FlowEHR but for Data Sources, TRE and others, we need to add a `flowehr` prefix to the state path to make it more obvious what state pertains to what project:

```
flowehr/infra-test/infrastructure/*/*tf.state
flowehr/app-dev/infrastructure/*/*tf.state
data-sources/infra-test/*/*tf.state
azure-tre/prod/*/*tf.state
```

etc.

### PR DESCRIPTION
**Pull request by jjgriff93**
- Adds flowehr prefix to tf state
  - To differentiate different projects in the state storage (i.e. FlowEHR, Data sources, TRE ...), this adds a prefix to the remote state block - resolves #251
- `make all` command works without having any apps defined (by making the serve block optional unless an app is present in the apps.yaml)
- `make all` now calls `transform-artifacts` - resolves #249 
- Makes data sources `dns_zones` optional
- If `private_dns_zones_rg` is defined, data source dns zone linking will look in that rg instead for existing zones to link to. Resolves #250

## Before merge

- [ ] Manually move infra-test and app-dev state from `/` to `/flowehr`

### CODE REVIEW

**Review by damoodamoo — APPROVED** [review]

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4720607854 (with refid `ccb9b05f`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/248#issuecomment-1511164418) from @jjgriff93)

**Comment by jjgriff93** [comment]
/test-force-approve
Previous job ran successfully, only minor update to gh action tf log level

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:white_check_mark: Marking tests as complete (for commit c3996fc7c1217b9394de355497c53df36bdcae9b)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/248#issuecomment-1511392668) from @jjgriff93)

**Pull request merged**
