### PR TITLE
Fix multiple app config parsing bug (move app config type definition to parent module)

### LINKED ISSUE #277: Adding more than one app configuration causes inconsistent types error
**Describe the bug**
After adding the los model seedling to the app config, we get the following error on apps deploy:

```
time=2023-04-24T15:28:00Z level=error msg=Error: Inconsistent conditional result types
  
   prefix=[/workspaces/UCLH-FlowEHR/apps] 
  
  time=2023-04-24T15:28:00Z level=error msg=  on /workspaces/UCLH-FlowEHR/apps/terragrunt.hcl line 29, in locals:
   prefix=[/workspaces/UCLH-FlowEHR/apps] 
  
  time=2023-04-24T15:28:00Z level=error msg=  29:   shared_apps_config      = fileexists(local.shared_apps_config_path) ? yamldecode(file(local.shared_apps_config_path)) : tomap({})
   prefix=[/workspaces/UCLH-FlowEHR/apps] 
  
  time=2023-04-24T15:28:00Z level=error msg=
   prefix=[/workspaces/UCLH-FlowEHR/apps] 
  time=2023-04-24T15:28:00Z level=error msg=with  prefix=[/workspaces/UCLH-FlowEHR/apps] 
  time=2023-04-24T15:28:00Z level=error msg=local.shared_apps_config_path as "/workspaces/UCLH-FlowEHR/apps/apps.yaml" prefix=[/workspaces/UCLH-FlowEHR/apps] 
  time=2023-04-24T15:28:00Z level=error msg=.
  
   prefix=[/workspaces/UCLH-FlowEHR/apps] 
  time=2023-04-24T15:28:00Z level=error msg=The true result value has the wrong type: element types must all match for
  conversion to map.
  
   prefix=[/workspaces/UCLH-FlowEHR/apps] 
  time=2023-04-24T15:28:00Z level=error msg=Encountered error while evaluating locals in file /workspaces/UCLH-FlowEHR/apps/terragrunt.hcl prefix=[/workspaces/UCLH-FlowEHR/apps] 
  
  time=2023-04-24T15:28:00Z level=error msg=Error processing module at '/workspaces/UCLH-FlowEHR/apps/terragrunt.hcl'. How this module was found: Terragrunt config file found in a subdirectory of /workspaces/UCLH-FlowEHR. Underlying error: /workspaces/UCLH-FlowEHR/apps/terragrunt.hcl:29,73-120: Inconsistent conditional result types; The true result value has the wrong type: element types must all match for conversion to map.
  time=2023-04-24T15:28:00Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Run: https://github.com/UCLH-Foundry/UCLH-FlowEHR/actions/runs/4788154607/jobs/8514367785#step:9:231

### PR DESCRIPTION
**Pull request by jjgriff93**
# Fixes #277

## What is being addressed

Fixes a bug where more than one app being defined causes terraform to fail parsing into a map.

## How is this addressed

- Moves the object type definition into the parent variables.tf which allows Terraform to convert the object into a map of objects correctly

### CODE REVIEW

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:runner: Running tests: https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4790830060 (with refid `7017191b`)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/278#issuecomment-1520791155) from @jjgriff93)

**Review by t-young31 — APPROVED** [review]
don't you just love tf

**Review by damoodamoo — APPROVED** [review]

**Comment by jjgriff93** [comment]
:robot: pr-bot :robot:

:white_check_mark: Marking tests as complete (for commit fd2d6b3c0f4c92c7a8ad7930a048d7857c9a4012)

(in response to [this comment](https://github.com/UCLH-Foundry/FlowEHR/pull/278#issuecomment-1521554003) from @jjgriff93)

**Pull request merged**
