### PR TITLE
Detect symbolic links to local repositories in pipeline_repo_checkout.sh

### PR DESCRIPTION
**Pull request by jongillham**
This aids local development by allowing data pipeline repositories to be symlinked under the `transform/pipelines` directory.

### CODE REVIEW

**Comment by tanya-borisova** [comment]
The way I saw this to work is you just specify your repository in the config and it checks out a copy of that. However if you want to support symlinks as well then I guess it's fine too

**Comment by tanya-borisova** [comment]
@jongillham  could you make a no-op change in infrastructure/transform so that we can trigger the CI pipeline testing that part of code

**Comment by jongillham** [comment]
Closing because I like the explanation @tanya-borisova gave.

**Pull request closed without merging**
